### ISSUE TITLE
make comment box fixed to screen bottom

### ISSUE THREAD

**Issue by Ewan5536** [kodiri/flat-pack-forum#65]
fixed input box.

**Comment by ykencw** [comment]
Note, we should be able to see all the Posts in the Thread, be careful that the input box doesn't cover the bottom Post in the Thread when we scroll to the bottom of the Thread Page!

**Comment by NilouferS** [comment]
We'll add an ability to spawn a Post Box in the middle of the thread later on if someone wishes to reply to a comment part-way through the thread.
